version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: "sopa"
      POSTGRES_DB: "inventario"
    container_name: inventario-base
    volumes:
      - ./postgres:/var/lib/postgresql/data
